http:
  host: localhost
  port: "8080"

kubernetes:
  api_server:
    host: localhost
    port: "9000"

postgres:
  host: localhost
  port: "5432"
  user: reactor
  password: reactor
  database: reactor

reactor:
  react_to: ua-server
  namespace: default
  product:
    name: ua-client
    image: middleware_client:1.5
