http:
  host: 0.0.0.0
  port: "8080"

kubernetes:
  api_server:
    host: localhost
    port: "8001"

postgres:
  host: localhost
  port: "5432"
  user: reactor
  password: reactor
  database: reactor

reactor:
  react_to: ua-server
  namespace: default
  product:
    name: ua-client
    image: registry.cn-hangzhou.aliyuncs.com/scut-cpps/middleware_client:1.5
